server:
  port: 8090

spring:
  datasource:
    username: root
    password: 3309055200z
    url: jdbc:mysql://81.70.199.191:3306/hqb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.hqb.pojo
  mapper-locations: classpath:mapper/*.xml
